package techmaker.util;

public enum StateMachine {
    IDLE, TRAVELLING, START_INTAKE,INTAKE_AVANCE,
    INTAKING, RETURNING_INTAKE, INTAKE_RETURNED,
    CLAW_SAMPLE, CLAW_SPECIMENT, DELIVER_SAMPLE,
    DELIVERY_SPECIMENT, CLAW_RETRACT, AUTO_CYCLE_START,
    AUTO_INTAKING, AUTO_GRAB, AUTO_RAISE
}
